apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "adservice.fullname" . }}
  labels:
    {{- include "adservice.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "adservice.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "adservice.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "adservice.serviceAccountName" . }}
      terminationGracePeriodSeconds: {{ .Values.tgp }}
      imagePullSecrets:
           - name: {{ .Values.docker_registry }}
      containers:
        - name: {{ .Values.container_name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          ports:
             -  containerPort: {{ .Values.containerPort }}
          env:
            - name: PORT
              value: {{ .Values.containerPort | quote }}

          resources:
              requests:
                  cpu: {{ .Values.resource.requests.cpu }}
                  memory: {{ .Values.resource.requests.memory }}
              limits:
                  cpu: {{ .Values.resource.limits.cpu }}
                  memory: {{ .Values.resource.limits.memory }}
          livenessProbe:
            initialDelaySeconds: 20
            periodSeconds: 15
            exec:
               command: ["/bin/grpc_health_probe", "-addr=:9555"]
          readinessProbe:
             initialDelaySeconds: 20
             periodSeconds: 15
             exec:
                command: ["/bin/grpc_health_probe", "-addr=:9555"]